import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { Nunito } from "next/font/google";

export const metadata = {
  title: "Oaks and Bear",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
